data:
  url: "https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv"
  test_size: 0.2
  random_state: 42

model:
  type: "RandomForest"
  params:
    n_estimators: 100
    max_depth: 10
    random_state: 42

mlflow:
  experiment_name: "wine-quality-experiment"
  tracking_uri: "file:./mlruns"